name: fibaconn
description: Firebase connector
publish_to: 'none' 
version: 2.2.1+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.3
  cloud_firestore: ^4.14.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  provider: ^6.1.1
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
